on:
  push:
    branches:
      - master






jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: "testing"
        run: pwd
      - name: "testing before"
        run: ls
      - uses: actions/checkout@v3
      - name: "testing after"
        run: ls