on:
  push:
    branches:
      - master






jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: "testing"
        run: pwd
      - name: "testing before"
        run: ls
      - uses: actions/checkout@v3
      - name: "testing after"
        run: ls
      - name: "login"
        run: docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_TA }}
      - name: "build"
        run: docker build -t ${{ secrets.DOCKER_USER }}/myimage .
      - name: "push d"
        run: docker push ${{ secrets.DOCKER_USER }}/myimage
      - name: "testing"
        run: pwd